<a href="https://colab.research.google.com/github/tanishkabishtt/fifa21-data-cleaning/blob/main/fifa21_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install kagglehub

import kagglehub
import pandas as pd
import os

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2025.11.12)

In [2]:
# Download the dataset using KaggleHub
path = kagglehub.dataset_download("yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring")
print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring?dataset_version_number=2...

100%|██████████| 5.28M/5.28M [00:01<00:00, 4.19MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring/versions/2

In [3]:
# List all files in the downloaded folder
for root, dirs, files in os.walk(path):
    for file in files:
        print(os.path.join(root, file))

/root/.cache/kagglehub/datasets/yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring/versions/2/fifa21_raw_data.csv
/root/.cache/kagglehub/datasets/yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring/versions/2/fifa21 raw data v2.csv

In [4]:
import pandas as pd

# Load the dataset using the correct filename
df = pd.read_csv(path + "/fifa21_raw_data.csv")  # or use "fifa21 raw data v2.csv" if preferred
df.head()

/tmp/ipython-input-2949989583.py:4: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path + "/fifa21_raw_data.csv")  # or use "fifa21 raw data v2.csv" if preferred

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273

In [5]:
# Standardize column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print(df.columns.tolist())

['photourl', 'longname', 'playerurl', 'nationality', 'positions', 'name', 'age', '↓ova', 'pot', 'team_&_contract', 'id', 'height', 'weight', 'foot', 'bov', 'bp', 'growth', 'joined', 'loan_date_end', 'value', 'wage', 'release_clause', 'attacking', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'skill', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'movement', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'power', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'mentality', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defending', 'marking', 'standing_tackle', 'sliding_tackle', 'goalkeeping', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'total_stats', 'base_stats', 'w/f', 'sm', 'a/w', 'd/w', 'ir', 'pac', 'sho', 'pas', 'dri', 'def', 'phy', 'hits']

In [6]:
print(df.columns.tolist())

['photourl', 'longname', 'playerurl', 'nationality', 'positions', 'name', 'age', '↓ova', 'pot', 'team_&_contract', 'id', 'height', 'weight', 'foot', 'bov', 'bp', 'growth', 'joined', 'loan_date_end', 'value', 'wage', 'release_clause', 'attacking', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'skill', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'movement', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'power', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'mentality', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defending', 'marking', 'standing_tackle', 'sliding_tackle', 'goalkeeping', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'total_stats', 'base_stats', 'w/f', 'sm', 'a/w', 'd/w', 'ir', 'pac', 'sho', 'pas', 'dri', 'def', 'phy', 'hits']

In [7]:
df['name'] = df['name'].astype(str).str.strip().str.title()
df['longname'] = df['longname'].astype(str).str.strip().str.title()

In [8]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [9]:
print(df.columns.tolist())

['photourl', 'longname', 'playerurl', 'nationality', 'positions', 'name', 'age', '↓ova', 'pot', 'team_&_contract', 'id', 'height', 'weight', 'foot', 'bov', 'bp', 'growth', 'joined', 'loan_date_end', 'value', 'wage', 'release_clause', 'attacking', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'skill', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'movement', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'power', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'mentality', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defending', 'marking', 'standing_tackle', 'sliding_tackle', 'goalkeeping', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'total_stats', 'base_stats', 'w/f', 'sm', 'a/w', 'd/w', 'ir', 'pac', 'sho', 'pas', 'dri', 'def', 'phy', 'hits']

In [10]:
df['nationality'] = df['nationality'].astype(str).str.strip().str.title()
df['positions'] = df['positions'].astype(str).str.strip().str.upper()
df['foot'] = df['foot'].astype(str).str.strip().str.title()

In [11]:
for col in ['nationality', 'positions', 'foot']:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.title()

In [12]:
# Convert numeric columns to proper types and handle missing values
numeric_cols = ['age', 'height', 'weight', 'vova', 'pot']
for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')
        df[col] = df[col].fillna(df[col].median())

In [13]:
if 'dob' in df.columns:
    df['dob'] = pd.to_datetime(df['dob'], errors='coerce')

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df['clean_status'] = 'Complete'

In [16]:
df.to_csv("fifa21_cleaned.csv", index=False)
print("Cleaned dataset saved as fifa21_cleaned.csv")

Cleaned dataset saved as fifa21_cleaned.csv

In [17]:
# Basic summary report with column checks
summary = {
    "Total Players": len(df),
    "Average Age": round(df['age'].mean(), 1) if 'age' in df.columns else "N/A",
    "Average Height (cm)": round(df['height'].mean(), 1) if 'height' in df.columns else "N/A",
    "Average Weight (kg)": round(df['weight'].mean(), 1) if 'weight' in df.columns else "N/A",
    "Average Potential": round(df['pot'].mean(), 1) if 'pot' in df.columns else "N/A",
    "Average Overall": round(df['vova'].mean(), 1) if 'vova' in df.columns else "N/A",
    "Unique Nationalities": df['nationality'].nunique() if 'nationality' in df.columns else "N/A",
    "Unique Clubs": df['club'].nunique() if 'club' in df.columns else "N/A"
}

print(summary)

{'Total Players': 18978, 'Average Age': np.float64(25.2), 'Average Height (cm)': nan, 'Average Weight (kg)': nan, 'Average Potential': np.float64(71.1), 'Average Overall': 'N/A', 'Unique Nationalities': 164, 'Unique Clubs': 'N/A'}

In [18]:
summary_df = pd.DataFrame([summary])
summary_df.to_csv("fifa21_summary.csv", index=False)

In [19]:
df

,photourl,longname,playerurl,nationality,positions,name,age,↓ova,pot,team_&_contract,...,d/w,ir,pac,sho,pas,dri,def,phy,hits,clean_status
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,Rw St Cf,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Low,5 ★,85,92,91,95,38,65,\n372,Complete
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo Dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,St Lw,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,Low,5 ★,89,93,81,89,35,77,\n344,Complete
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,Gk,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,3 ★,87,92,78,90,52,90,\n86,Complete
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,Cam Cm,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,4 ★,76,86,93,88,64,78,\n163,Complete
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar Da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,Lw Cam,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,Medium,5 ★,91,85,86,94,36,59,\n273,Complete
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China Pr,Cb,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,...,Low,1 ★,58,23,26,27,50,48,2,Complete
18975,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,St,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,1 ★,70,46,40,53,16,40,3,Complete
18976,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China Pr,Cb,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,...,Medium,1 ★,64,28,26,38,48,51,3,Complete
18977,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,Cm,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,1 ★,64,40,48,49,35,45,5,Complete
18978,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,Cdm,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,...,Medium,1 ★,57,32,43,48,44,49,2,Complete

In [20]:
from google.colab import files
files.download("fifa21_cleaned.csv")

In [21]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [22]:
import pandas as pd

# Load your cleaned CSV
df = pd.read_csv("fifa21_cleaned.csv")

# Save as Excel file
df.to_excel("fifa21_cleaned.xlsx", index=False)

/tmp/ipython-input-959356761.py:4: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("fifa21_cleaned.csv")

In [23]:
from openpyxl import load_workbook
from openpyxl.styles import Alignment

# Load the Excel file
wb = load_workbook("fifa21_cleaned.xlsx")
ws = wb.active

# Set row height and wrap text for all rows
for row in ws.iter_rows():
    for cell in row:
        cell.alignment = Alignment(wrap_text=True)
    ws.row_dimensions[row[0].row].height = 30  # Adjust height as needed

# Save the updated Excel file
wb.save("fifa21_cleaned_formatted.xlsx")

In [24]:
from google.colab import files
files.download("fifa21_cleaned_formatted.xlsx")

In [25]:
import pandas as pd

# Load the formatted Excel file
df = pd.read_excel("fifa21_cleaned_formatted.xlsx")

# Show first 5 rows
df.head()

,photourl,longname,playerurl,nationality,positions,name,age,↓ova,pot,team_&_contract,...,d/w,ir,pac,sho,pas,dri,def,phy,hits,clean_status
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,Rw St Cf,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Low,5 ★,85,92,91,95,38,65,\n372,Complete
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo Dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,St Lw,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,Low,5 ★,89,93,81,89,35,77,\n344,Complete
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,Gk,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,3 ★,87,92,78,90,52,90,\n86,Complete
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,Cam Cm,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,4 ★,76,86,93,88,64,78,\n163,Complete
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar Da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,Lw Cam,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,Medium,5 ★,91,85,86,94,36,59,\n273,Complete

In [26]:
import pandas as pd

# Load the formatted Excel file
df = pd.read_excel("fifa21_cleaned_formatted.xlsx")

# Show first 5 rows
df.head()

,photourl,longname,playerurl,nationality,positions,name,age,↓ova,pot,team_&_contract,...,d/w,ir,pac,sho,pas,dri,def,phy,hits,clean_status
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,Rw St Cf,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Low,5 ★,85,92,91,95,38,65,\n372,Complete
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo Dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,St Lw,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,Low,5 ★,89,93,81,89,35,77,\n344,Complete
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,Gk,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,3 ★,87,92,78,90,52,90,\n86,Complete
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,Cam Cm,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,4 ★,76,86,93,88,64,78,\n163,Complete
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar Da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,Lw Cam,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,Medium,5 ★,91,85,86,94,36,59,\n273,Complete

In [27]:
# Count missing values per column
print(df.isnull().sum())

photourl        0
longname        0
playerurl       0
nationality     0
positions       0
               ..
dri             0
def             0
phy             0
hits            0
clean_status    0
Length: 78, dtype: int64

In [28]:
# Count duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [29]:
# Look for non-ASCII characters in text columns
text_cols = df.select_dtypes(include=['object']).columns
for col in text_cols:
    weird = df[col].apply(lambda x: any(ord(c) > 127 for c in str(x)))
    if weird.any():
        print(f"Column {col} has non-standard characters")

Column longname has non-standard characters
Column nationality has non-standard characters
Column name has non-standard characters
Column team_&_contract has non-standard characters
Column value has non-standard characters
Column wage has non-standard characters
Column release_clause has non-standard characters
Column w/f has non-standard characters
Column sm has non-standard characters
Column ir has non-standard characters

In [30]:
# Summary of numeric columns
print(df.describe())

                age          ↓ova           pot             id  height  \
count  18978.000000  18978.000000  18978.000000   18978.000000     0.0
mean      25.194225     65.718042     71.135789  226403.457477     NaN
std        4.710618      6.968701      6.114189   27141.767404     NaN
min       16.000000     47.000000     47.000000      41.000000     NaN
25%       21.000000     61.000000     67.000000  210134.500000     NaN
50%       25.000000     66.000000     71.000000  232421.000000     NaN
75%       29.000000     70.000000     75.000000  246922.750000     NaN
max       53.000000     93.000000     95.000000  259216.000000     NaN

       weight           bov        growth     attacking      crossing  ...  \
count     0.0  18978.000000  18978.000000  18978.000000  18978.000000  ...
mean      NaN     66.751080      5.417747    248.935610     49.687375  ...
std       NaN      6.746785      5.663967     74.300567     18.131089  ...
min       NaN     48.000000      0.000000     42.000000      6.000000  ...
25%       NaN     62.000000      0.000000    222.000000     38.000000  ...
50%       NaN     67.000000      4.000000    263.000000     54.000000  ...
75%       NaN     71.000000      9.000000    297.000000     63.000000  ...
max       NaN     93.000000     26.000000    437.000000     94.000000  ...

       gk_positioning   gk_reflexes   total_stats    base_stats           pac  \
count    18978.000000  18978.000000  18978.000000  18978.000000  18978.000000
mean        16.217620     16.519654   1595.272368    355.699652     67.453683
std         17.002582     17.854549    269.874424     40.760683     10.678065
min          2.000000      2.000000    747.000000    232.000000     25.000000
25%          8.000000      8.000000   1452.000000    327.000000     61.000000
50%         11.000000     11.000000   1627.000000    356.000000     68.000000
75%         14.000000     14.000000   1781.000000    384.000000     75.000000
max         91.000000     90.000000   2316.000000    498.000000     96.000000

                sho           pas           dri           def           phy
count  18978.000000  18978.000000  18978.000000  18978.000000  18978.000000
mean      53.457582     57.680472     62.874750     49.864738     64.368427
std       13.827581     10.081845      9.927607     16.442378      9.601882
min       16.000000     25.000000     25.000000     12.000000     28.000000
25%       44.000000     51.000000     57.000000     35.000000     58.000000
50%       56.000000     58.000000     64.000000     53.000000     65.000000
75%       64.000000     64.000000     69.000000     63.000000     71.000000
max       93.000000     93.000000     95.000000     91.000000     91.000000

[8 rows x 57 columns]

In [31]:
df

,photourl,longname,playerurl,nationality,positions,name,age,↓ova,pot,team_&_contract,...,d/w,ir,pac,sho,pas,dri,def,phy,hits,clean_status
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,Rw St Cf,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Low,5 ★,85,92,91,95,38,65,\n372,Complete
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo Dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,St Lw,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,Low,5 ★,89,93,81,89,35,77,\n344,Complete
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,Gk,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,3 ★,87,92,78,90,52,90,\n86,Complete
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,Cam Cm,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,4 ★,76,86,93,88,64,78,\n163,Complete
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar Da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,Lw Cam,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,Medium,5 ★,91,85,86,94,36,59,\n273,Complete
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18973,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China Pr,Cb,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,...,Low,1 ★,58,23,26,27,50,48,2,Complete
18974,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,St,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,1 ★,70,46,40,53,16,40,3,Complete
18975,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China Pr,Cb,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,...,Medium,1 ★,64,28,26,38,48,51,3,Complete
18976,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,Cm,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,1 ★,64,40,48,49,35,45,5,Complete
18977,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,Cdm,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,...,Medium,1 ★,57,32,43,48,44,49,2,Complete

In [33]:
import pandas as pd

# Load your Excel file
df = pd.read_excel("fifa21_cleaned_formatted.xlsx")

# 1. Show column names
print("Columns:", df.columns.tolist())

# 2. Missing values
print("\nMissing values per column:")
print(df.isnull().sum())

# 3. Duplicate rows
print("\nDuplicate rows:", df.duplicated().sum())

# 4. Numeric column types
numeric_cols = ['age','height','weight','pot']
if 'â†“ova' in df.columns:
    df.rename(columns={'â†“ova':'overall'}, inplace=True)
numeric_cols.append('overall')
print("\nNumeric column types:")
print(df[numeric_cols].dtypes)

# 5. Sample text values
print("\nSample nationalities:", df['nationality'].unique()[:10])
print("Sample positions:", df['positions'].unique()[:10])

# 6. Non-standard characters
text_cols = df.select_dtypes(include=['object']).columns
for col in text_cols:
    weird = df[col].apply(lambda x: any(ord(c) > 127 for c in str(x)))
    if weird.any():
        print(f"⚠️ Column {col} has non-standard characters")

# 7. Summary stats
print("\nSummary stats:")
print(df.describe())

Columns: ['photourl', 'longname', 'playerurl', 'nationality', 'positions', 'name', 'age', '↓ova', 'pot', 'team_&_contract', 'id', 'height', 'weight', 'foot', 'bov', 'bp', 'growth', 'joined', 'loan_date_end', 'value', 'wage', 'release_clause', 'attacking', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'skill', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'movement', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'power', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'mentality', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defending', 'marking', 'standing_tackle', 'sliding_tackle', 'goalkeeping', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'total_stats', 'base_stats', 'w/f', 'sm', 'a/w', 'd/w', 'ir', 'pac', 'sho', 'pas', 'dri', 'def', 'phy', 'hits', 'clean_status']

Missing values per column:
photourl        0
longname        0
playerurl       0
nationality     0
positions       0
               ..
dri             0
def             0
phy             0
hits            0
clean_status    0
Length: 78, dtype: int64

Duplicate rows: 0

Numeric column types:

KeyError: "['overall'] not in index"

In [34]:
df.rename(columns={'â†“ova': 'overall'}, inplace=True)

In [35]:
print(df[['age','height','weight','pot','overall']].dtypes)

KeyError: "['overall'] not in index"

In [36]:
df.rename(columns={'â†“ova': 'overall'}, inplace=True)

In [37]:
# Step 1: Print all column names to find the correct one
print(df.columns.tolist())

['photourl', 'longname', 'playerurl', 'nationality', 'positions', 'name', 'age', '↓ova', 'pot', 'team_&_contract', 'id', 'height', 'weight', 'foot', 'bov', 'bp', 'growth', 'joined', 'loan_date_end', 'value', 'wage', 'release_clause', 'attacking', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'skill', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'movement', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'power', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'mentality', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defending', 'marking', 'standing_tackle', 'sliding_tackle', 'goalkeeping', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'total_stats', 'base_stats', 'w/f', 'sm', 'a/w', 'd/w', 'ir', 'pac', 'sho', 'pas', 'dri', 'def', 'phy', 'hits', 'clean_status']

In [38]:
df.rename(columns={'â†“ova': 'overall'}, inplace=True)

In [39]:
print(df[['age', 'height', 'weight', 'pot', 'overall']].dtypes)
print(df[['age', 'height', 'weight', 'pot', 'overall']].describe())

KeyError: "['overall'] not in index"

In [40]:
print(df[['age', 'height', 'weight', 'pot', 'overall']].dtypes)
print(df[['age', 'height', 'weight', 'pot', 'overall']].describe())

KeyError: "['overall'] not in index"

In [41]:
df.rename(columns={'ã†ova': 'overall'}, inplace=True)

In [42]:
print(df[['age', 'height', 'weight', 'pot', 'overall']].dtypes)
print(df[['age', 'height', 'weight', 'pot', 'overall']].describe())

KeyError: "['overall'] not in index"

In [43]:
print(df.columns.tolist())

['photourl', 'longname', 'playerurl', 'nationality', 'positions', 'name', 'age', '↓ova', 'pot', 'team_&_contract', 'id', 'height', 'weight', 'foot', 'bov', 'bp', 'growth', 'joined', 'loan_date_end', 'value', 'wage', 'release_clause', 'attacking', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'skill', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'movement', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'power', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'mentality', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defending', 'marking', 'standing_tackle', 'sliding_tackle', 'goalkeeping', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'total_stats', 'base_stats', 'w/f', 'sm', 'a/w', 'd/w', 'ir', 'pac', 'sho', 'pas', 'dri', 'def', 'phy', 'hits', 'clean_status']

In [44]:
summary = {
    "Total Players": len(df),
    "Average Age": round(df['age'].mean(), 1),
    "Average Height (cm)": round(df['height'].mean(), 1),
    "Average Weight (kg)": round(df['weight'].mean(), 1),
    "Average Potential": round(df['pot'].mean(), 1),
    "Average Overall": round(df['ova'].mean(), 1),
    "Unique Nationalities": df['nationality'].nunique(),
    "Unique Positions": df['positions'].nunique()
}

KeyError: 'ova'

In [45]:
summary = {
    "Total Players": len(df),
    "Average Age": round(df['age'].mean(), 1),
    "Average Height (cm)": round(df['height'].mean(), 1),
    "Average Weight (kg)": round(df['weight'].mean(), 1),
    "Average Potential": round(df['pot'].mean(), 1),
    "Average Overall": round(df['ova'].mean(), 1),
    "Unique Nationalities": df['nationality'].nunique(),
    "Unique Positions": df['positions'].nunique()
}

KeyError: 'ova'

In [46]:
for col in df.columns:
    print(repr(col))

'photourl'
'longname'
'playerurl'
'nationality'
'positions'
'name'
'age'
'↓ova'
'pot'
'team_&_contract'
'id'
'height'
'weight'
'foot'
'bov'
'bp'
'growth'
'joined'
'loan_date_end'
'value'
'wage'
'release_clause'
'attacking'
'crossing'
'finishing'
'heading_accuracy'
'short_passing'
'volleys'
'skill'
'dribbling'
'curve'
'fk_accuracy'
'long_passing'
'ball_control'
'movement'
'acceleration'
'sprint_speed'
'agility'
'reactions'
'balance'
'power'
'shot_power'
'jumping'
'stamina'
'strength'
'long_shots'
'mentality'
'aggression'
'interceptions'
'positioning'
'vision'
'penalties'
'composure'
'defending'
'marking'
'standing_tackle'
'sliding_tackle'
'goalkeeping'
'gk_diving'
'gk_handling'
'gk_kicking'
'gk_positioning'
'gk_reflexes'
'total_stats'
'base_stats'
'w/f'
'sm'
'a/w'
'd/w'
'ir'
'pac'
'sho'
'pas'
'dri'
'def'
'phy'
'hits'
'clean_status'

In [48]:
import pandas as pd
from openpyxl import load_workbook
from openpyxl.chart import BarChart, PieChart, Reference

# Load cleaned Excel file
df = pd.read_excel("fifa21_cleaned_formatted.xlsx")
wb = load_workbook("fifa21_cleaned_formatted.xlsx")
ws_summary = wb.create_sheet("Summary")

# Summary stats
summary = {
    "Total Players": len(df),
    "Average Age": round(df['age'].mean(), 1),
    "Average Height (cm)": round(df['height'].mean(), 1),
    "Average Weight (kg)": round(df['weight'].mean(), 1),
    "Average Potential": round(df['pot'].mean(), 1),
    "Average Overall": round(df['↓ova'].mean(), 1),
    "Unique Nationalities": df['nationality'].nunique(),
    "Unique Positions": df['positions'].nunique()
}

for key, value in summary.items():
    ws_summary.append([key, value])

# Top 10 Positions
ws_summary.append([])
ws_summary.append(["Top 10 Positions", "Count"])
top_positions = df['positions'].value_counts().head(10)
for pos, count in top_positions.items():
    ws_summary.append([pos, count])

bar = BarChart()
bar.title = "Top 10 Positions"
bar.x_axis.title = "Position"
bar.y_axis.title = "Count"
data = Reference(ws_summary, min_col=2, min_row=len(summary)+3, max_row=len(summary)+12)
cats = Reference(ws_summary, min_col=1, min_row=len(summary)+4, max_row=len(summary)+12)
bar.add_data(data, titles_from_data=True)
bar.set_categories(cats)
ws_summary.add_chart(bar, "E5")

# Top 10 Nationalities
ws_summary.append([])
ws_summary.append(["Top 10 Nationalities", "Count"])
top_nations = df['nationality'].value_counts().head(10)
for nat, count in top_nations.items():
    ws_summary.append([nat, count])

start_row = ws_summary.max_row - 9
pie = PieChart()
pie.title = "Top 10 Nationalities"
data = Reference(ws_summary, min_col=2, min_row=start_row, max_row=start_row+9)
cats = Reference(ws_summary, min_col=1, min_row=start_row, max_row=start_row+9)
pie.add_data(data, titles_from_data=False)
pie.set_categories(cats)
ws_summary.add_chart(pie, f"E20")

# Save final file
wb.save("fifa21_cleaned_with_summary_and_charts.xlsx")

In [51]:
from google.colab import files
files.download("fifa21_cleaned_with_summary_and_charts.xlsx")